### ISSUE TITLE
Enhancement Request: Network Proxy Configurations

### ISSUE THREAD

**Issue by dmoruzzi** [jtmoon79/PythonEmbed4Win#5]
Supporting runtime network proxy configurations as an option will make this project more accessible to users operating within restrictive network environments, such as corporate lab environments.

I incorporated this through including:
```powershell
PS> (New-Object System.Net.WebClient).Proxy.Credentials = `
>>  [System.Net.CredentialCache]::DefaultNetworkCredentials
```

However, I think a parameter configuration may be a better approach as the user base's default configurations may be different than the network firewall credentials. An example of this is when an employee's account lacks the permission for external connectivity within a subnet but their application support account credentials permit them.

**Comment by jtmoon79** [comment]
Proxying; I hadn't thought about it.
You're welcome to submit a PR. 🙂

**Comment by dmoruzzi** [comment]
Thank you for the suggestion. I actually forked the project and was going to just submit a merge request. However, I then realized that I was getting distracted from my core projects at work. Unfortunately, being completely honest, I don't think I will be able to find the time to do this implementation. Work is limited on resources making long hours and I don't have the desire to code personally after 12+ hours at work. I'm sorry for that, especially as this project saved me a lot of headache. I hope someone else in the OSS community has the available time and knowledge. 


Some positive news is I documented the solution I used for this feature within this Issue. As such, when someone else finds this project and needs to use a proxy configuration, they may find this suggestion from search and at least try an implementation that worked for someone else. I don't believe this implementation is mature enough to be merged into the code base, though.

Thank you for the amazing project and you're truly a rockstar for saving me (and others) so much headache and time.

**Comment by jtmoon79** [comment]
> Unfortunately, being completely honest, I don't think I will be able to find the time to do this implementation. 

No worries at all.

> I documented the solution I used for this feature within this Issue.

Yes thanks for that.

> Thank you for the amazing project and you're truly a rockstar for saving me (and others) so much headache and time.

Nice to hear the feedback!
Can you describe the situation you used this script in? What made this script so useful over other Python installers? I'm merely curious about other situations where this script has been useful.

**Comment by jtmoon79** [comment]
Closing.  I'm very unlikely to do this, but if I did then I'd need more info.
